[package]
name = "yew_route"
version = "0.1.0"
authors = ["Garrett Berg <googberg@gmail.com>"]

[dependencies]
url = "1.7.0"
yew = {version="0.3.*", git="https://github.com/DenisKolodin/yew"}
stdweb = "0.4.2"
