[package]
name = "counter_router"
version = "0.1.0"
authors = ["Garrett Berg <vitiral@gmail.com>"]

[dependencies]
stdweb = "0.4.2"
yew = {git="https://github.com/DenisKolodin/yew"}
yew_router = { path = "../.."}
